ALTER TABLE "BasePlayer"
ADD COLUMN IF NOT EXISTS "salary" INTEGER NOT NULL DEFAULT 1000000;

ALTER TABLE "BasePlayer"
ADD COLUMN IF NOT EXISTS "contractYears" INTEGER NOT NULL DEFAULT 3;

ALTER TABLE "SavePlayer"
ADD COLUMN IF NOT EXISTS "salary" INTEGER NOT NULL DEFAULT 1000000;

ALTER TABLE "SavePlayer"
ADD COLUMN IF NOT EXISTS "contractYears" INTEGER NOT NULL DEFAULT 3;