ALTER TABLE "SavePlayer"
ADD COLUMN IF NOT EXISTS "fitness" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "SavePlayer"
ADD COLUMN IF NOT EXISTS "injured" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "SavePlayer"
ADD COLUMN IF NOT EXISTS "injuryWeeks" INTEGER NOT NULL DEFAULT 0;